# Generated by Django 3.1.5 on 2021-03-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0002_auto_20210326_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='doj',
            new_name='Doj',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='employeeId',
            new_name='EmployeeId',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='employeeName',
            new_name='EmployeeName',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='photofield',
            new_name='PhotoField',
        ),
    ]
